repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./server/.isort.cfg .
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^src/blib2to3/|/__init__\.py$