repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: ^client/|/__init__\.py$

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./server/.isort.cfg .
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        exclude: ^src/blib2to3/